# Use in addition to docker-compose.yaml to test the deployment with unicorn and NginX as reverse proxy, see Readme.md
version: '2.2'
services:  
  backend_1: &migrating_backend
    image: macworp/backend:dev
    volumes:
      - ./macworp:/home/mambauser/macworp
      - ./deploy_test_uploads:/home/mambauser/uploads
      # Pass the local config
      - ./config.docker-compose.yaml:/home/mambauser/macworp.local.config.yaml:ro
      - ./dev_auth.yaml:/home/mambauser/dev_auth.yaml:ro
    environment:
      OAUTHLIB_INSECURE_TRANSPORT: 1
      MACWORP_HOSTNAME: ${MACWORP_HOSTNAME:-localhost}
      MACWORP_FUSIONAUTH_PORT: ${MACWORP_FUSIONAUTH_PORT:-9011}
      RUN_MIGRATION: "true"
      MIGRATION_DB_HOSTNAME: psql
      PYTHONUNBUFFERED: "true"
    command: ["serve", "--gunicorn"]
    depends_on:
      psql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  backend_2: &backend
    <<: *migrating_backend
    environment:
      RUN_MIGRATION: "false"
      OAUTHLIB_INSECURE_TRANSPORT: 1
      MACWORP_HOSTNAME: ${MACWORP_HOSTNAME:-localhost}
      MACWORP_FUSIONAUTH_PORT: ${MACWORP_FUSIONAUTH_PORT:-9011}
      PYTHONUNBUFFERED: "true"
    depends_on:
      - backend_1
  backend_3: *backend
  backend_4: *backend
  frontend:
    image: macworp/frontend:dev
    environment:
      MACWORP_BACKEND_BASE_URL: https://${MACWORP_HOSTNAME:-localhost}:16160
      MACWORP_BACKEND_WS_URL: https://${MACWORP_HOSTNAME:-localhost}:16160
      MACWORP_FRONTEND_INTERFACE: 0.0.0.0
      MACWORP_UPLOAD_MAX_FILE_SITE: 10737418240
  nginx:
    image: nginx:stable
    ports:
      - 16160:16160
      - 16161:16161
    environment:
      MACWORP_HOSTNAME: ${MACWORP_HOSTNAME}
    volumes:
      - ./docker/nginx/certificate-creation.sh:/docker-entrypoint.d/99-certificates.sh:ro
      - ./docker/nginx/high-available.conf.template:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      - backend_1
      - backend_2
      - backend_3
      - backend_4
      - frontend
      - fusionauth
    links:
      - backend_1
      - backend_2
      - backend_3
      - backend_4
      - frontend
      - fusionauth
