name: macworp
channels:
  - defaults
  - conda-forge
dependencies:
  - libpq
  - nodejs=18.*
  - conda-forge::yarn
  - python=3.12
  - pip
  - setuptools
  - cython
  - yaml
  - bioconda::snakemake=8.25.3
  - pip:
    - -e ./backend[dev]
    - -e ./worker[dev,demo]
    - -r ./requirements.txt