name: nf_cloud
channels:
  - defaults
  - conda-forge
dependencies:
  - libpq
  - nodejs=18.*
  - node-gyp
  - yarn
  - python=3.10
  - pip
  - setuptools
  - cython
  - yaml
  - pip:
    - -e ./backend[dev]
    - -e ./worker[dev]
