name: nf_cloud_v2
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - cython
  - yaml
  - libpq
  - pip:
    - -e ./backend[dev]
    - fastapi
    - uvicorn[standard]
    - python-multipart
    - python-jose[cryptography]
    - passlib[bcrypt]