site_name: MAcWorP - Massive Accessible Workflow Platform
theme: readthedocs
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: !relative $config_dir
plugins: 
  - mike:
      version_selector: true
      canonical_version: null