[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nf_cloud_backend"
version = "2.0.0"
dependencies = [
	"fastapi >= 0.110.2",
	"uvicorn >= 0.29.0",
]

[project.optional-dependencies]
dev = [
    "honcho",
    "pylint"
]