from logging import DEBUG, INFO
from pathlib import Path
from typing import Optional, Union

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

from macworp.backend.database import init_database
from macworp.configuration import Configuration
from macworp.backend.controllers.depends import get_configuration
from macworp.backend.controllers import users
from macworp.backend.controllers import project
from macworp.backend.controllers import workflow

TEMPORATY_DEV_MODE_CONFIG_PATH = Path(__file__).parent.joinpath(".config.yml.tmp")


def get_app(config: Configuration) -> FastAPI:
    """
    Initializes the database connection and returns a FastAPI application instance ready to use.
    """

    init_database(config.backend.database)

    app = FastAPI()

    app.include_router(project.router)
    app.include_router(workflow.router)
    app.include_router(users.router)

    def get_given_configuration():
        """Function to return the configuration passed to the app via CLI"""
        return config

    # Because the settings coming via CLI and getting passed through the executor etc.
    # passing the setting as described in the FastAPI documentation is not possible.
    # Every path that uses the settings need an argument
    # `settings: Settings = Depends(get_dummy_settings)`
    # which is ultimately overridden by the `get_settings` function.
    app.dependency_overrides[get_configuration] = get_given_configuration

    app.add_middleware(
        CORSMiddleware,
        allow_origins=config.backend.allowed_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    @app.middleware("http")
    async def add_process_time_header(request: Request, call_next):
        print(f"Request:\n\t{request.url}\n\t{request.method}\n\t{request.headers}")
        response = await call_next(request)
        return response

    return app


dev_global_app: Optional[FastAPI] = (
    get_app(Configuration.from_file(TEMPORATY_DEV_MODE_CONFIG_PATH))
    if TEMPORATY_DEV_MODE_CONFIG_PATH.is_file()
    else None
)  # type: ignore[assignment]
"""For development purposes only. Allows uvicorn to reload the app on changes."""


def start_app(config: Configuration):
    """Starts the FastAPI application with the given configuration."""

    config.projects_path.mkdir(parents=True, exist_ok=True)

    log_level = DEBUG if config.debug else INFO

    app_or_mod: Union[FastAPI, str] = "macworp.backend.app:dev_global_app"
    if not config.development:
        TEMPORATY_DEV_MODE_CONFIG_PATH.unlink(missing_ok=True)  # type: ignore[call-arg]
        app_or_mod = get_app(config)
    else:
        with TEMPORATY_DEV_MODE_CONFIG_PATH.open("w", encoding="utf-8") as f:
            f.write(
                (
                    "# This file is automatically generated by MAcWorP in development mode"
                    "to support automatically reloading of the backend on changes.\n"
                )
            )
            f.write(str(config))

    uvicorn.run(
        app_or_mod,
        host=config.backend.interface,
        port=config.backend.port,
        reload=config.development,
        log_level=log_level,
        access_log=log_level == DEBUG,
        reload_dirs=[str(Path(__file__).parent.parent)],
        reload_excludes=[
            str(TEMPORATY_DEV_MODE_CONFIG_PATH.relative_to(Path.cwd()))  # type: ignore[arg-type]
        ],
    )
